import Provider from "@/components/Provider";
import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Social Media",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider>
        <body>
          <Navbar />
          <div className="main" />
          <main className="app">{children}</main>
        </body>
      </Provider>
    </html>
  );
}
