import Navbar from "@/components/Navbar";
import Provider from "@/components/Provider";
import LeftSidebar from "@/components/LeftSidebar";
import RightSidebar from "@/components/RightSidebar";
import "./globals.css";

export const metadata = {
  title: "Social Media",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider>
        <body>
          <header>
            <Navbar />
          </header>

          <div className="grid-background" />

          <main>
            <LeftSidebar />
            {children}
            <RightSidebar />
          </main>
        </body>
      </Provider>
    </html>
  );
}
